doctrine:
    dbal:
        default_connection: prod

        connections:
            dev:
                url: '%env(DATABASE_URL)%'
                charset: utf8mb4
                server_version: '%env(SERVER_VERSION)%'            
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string
            prod:
                url: '%env(DATABASE_URL)%'
                charset: utf8mb4
                server_version: '%env(SERVER_VERSION)%'
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci
                mapping_types:
                    enum: string
           

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
